(() => {
  'use strict';
  const desktop={key:'9d555c793875e3095248cf45d3085138',width:728,height:90};
  const mobile={key:'d35ee6a7d7ffd21d33f108439621e9cd',width:300,height:250};
  const host=document.querySelector('[data-bigg-banner]');
  if(!host||host.dataset.bannerLoaded==='1')return;
  host.dataset.bannerLoaded='1';
  const ad=matchMedia('(min-width:760px)').matches?desktop:mobile;
  const label=document.createElement('span');
  label.className='ad-slot-label';
  label.textContent='Advertisement · '+ad.width+'×'+ad.height;
  const frame=document.createElement('iframe');
  frame.title='Advertisement';
  frame.width=String(ad.width);
  frame.height=String(ad.height);
  frame.loading='eager';
  frame.style.cssText='display:block;width:'+ad.width+'px;max-width:100%;height:'+ad.height+'px;margin:8px auto 0;border:0;overflow:hidden';
  frame.setAttribute('sandbox','allow-scripts allow-popups allow-popups-to-escape-sandbox allow-top-navigation-by-user-activation');
  frame.setAttribute('referrerpolicy','no-referrer-when-downgrade');
  frame.srcdoc='<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;padding:0;overflow:hidden;background:transparent}</style></head><body><script>atOptions={key:"'+ad.key+'",format:"iframe",height:'+ad.height+',width:'+ad.width+',params:{}};<\/script><script src="https://www.highperformanceformat.com/'+ad.key+'/invoke.js"><\/script></body></html>';
  host.replaceChildren(label,frame);
})();
